version: '3'

services:
  nginx:
    image: nginx:alpine
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=dev.reservofficer.se
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev.reservofficer.se
      - LETSENCRYPT_EMAIL=digitalocean@prosapio.se
    volumes:
      - /home/sysadmin/dev/www/static/files:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy
