version: '3'

services:
  nginx:
    image: nginx:alpine
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${FQDN}
      - LETSENCRYPT_HOST=${FQDN}
    volumes:
      - ./www/static/files:/usr/share/nginx/html:ro
    networks:
      - proxy
    #restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy
